image:
  repository: abesesr/clamscan-docker
  pullPolicy: IfNotPresent
  tag: latest

env:
  SCAN_AT_STARTUP: 1 # if 1, then start with a scan when the container is created (default is 1)
  FRESHCLAM_AT_STARTUP: 1 # if 1, then update the virus database when the container startup (default is 1)
  SCAN_ONLY_NEW_FILES: 1 # if 1, then the scan will scan a first time the whole FOLDER_TO_SCAN content, and the next time (see CRON_CLAMSCAN) it will only scan the new files found. Thanks to this feature, the process will be lighter (less CPU usage) especially when there is lot and lot of files in FOLDER_TO_SCAN (default is 1)
  FOLDER_TO_SCAN: "/scandir" # this is the folder to scan with clamscan (default is /folder-to-scan/)
  CRON_CLAMSCAN: 0 0 30 * * * # crontab parameters to run the clamscan command which is used to scan the FOLDER_TO_SCAN (default is */5 * * * * - it means each 5 minutes)
  CRON_FRESHCLAM: 0 0 * * * * # crontab parameters to run the freshclam command which is used to update virus databases (default is 0 * * * * * - it means each hours)
  ALERT_MAILTO: notification@mail.com # email address to send the alerts to (empty value as default so nothing is sent as)
  ALERT_SUBJECT: "Malware found by ClamAV" # email subject for sending alerts to (Alert from clamscan ! is the default value)
  SMTP_TLS: on # to enable TLS, set the value to on (default is off)
  SMTP_HOST: smtp.mail.com # host or ip of the smtp server used to send the alerts (default is 127.0.0.1)
  SMTP_PORT: 25 # port of the smtp server used to send the alerts (default is25)
  SMTP_USER: username # smtp server login (empty value as default)
  SMTP_PASSWORD: password # smtp server password (empty value as default)

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    ports:
      main:
        port: 3310
        targetPort: 3310
  milter:
    enabled: true
    ports:
      milter:
        enabled: true
        port: 7357
        targetPort: 7357

persistence:
  sigdatabase:
    enabled: true
    mountPath: "/var/lib/clamav"
  # existingClaim: clamav-sigdatabase
    accessMode: ReadWriteOnce
    size: 256Mi

  # -- Scan Dirs for ClamAV Scans
  #
  # --- Use local dir
  #
  # scandir:
  #   enabled: true
  #   mountPath: "/scandir"
  #   readOnly: true
  #
  # --- Use NFS Share
  #
  # scandir:
  #   enabled: false
  #   type: custom
  #   mountPath: "/scandir"
  #   volumeSpec:
  #     nfs:
  #       server: 10.0.0.1
  #       path: "/mnt/hddstore01"
  #   readOnly: true

# -- Configure Limits for resources
# resources:
#   requests:
#     memory: 128Mi
#     cpu: "0.01"
#   limits:
#     memory: 512Mi