image:
  repository: tccr.io/truecharts/clamav
  pullPolicy: IfNotPresent
  tag: v0.104.2@sha256:eb816a62ce0b7c331d893e8d51e54fe96b1cb5878c7394e935a48468b0b44f6d

env:
  CLAMAV_NO_CLAMD: false
  CLAMAV_NO_FRESHCLAMD: false
  CLAMAV_NO_MILTERD: true
  CLAMD_STARTUP_TIMEOUT: 1800
  FRESHCLAM_CHECKS: 1

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - clamdcheck.sh
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 10
      timeoutSeconds: 1
  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - clamdcheck.sh
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 10
      timeoutSeconds: 1
  startup:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - clamdcheck.sh
      initialDelaySeconds: 15
      periodSeconds: 30
      failureThreshold: 10
      timeoutSeconds: 1

service:
  main:
    ports:
      main:
        port: 3310
        targetPort: 3310
  milter:
    enabled: true
    ports:
      milter:
        enabled: true
        port: 7357
        targetPort: 7357

persistence:
  sigdatabase:
    enabled: true
    mountPath: "/var/lib/clamav"
  # existingClaim: clamav-sigdatabase
    accessMode: ReadWriteOnce
    size: 256Mi

  # -- Scan Dirs for ClamAV Scans
  #
  # --- Use local dir
  #
  # scandir:
  #   enabled: true
  #   mountPath: "/scandir"
  #   readOnly: true
  #
  # --- Use NFS Share
  #
  # scandir:
  #   enabled: false
  #   type: custom
  #   mountPath: "/scandir"
  #   volumeSpec:
  #     nfs:
  #       server: 10.0.0.1
  #       path: "/mnt/hddstore01"
  #   readOnly: true

# -- Configure Limits for resources
# resources:
#   requests:
#     memory: 128Mi
#     cpu: "0.01"
#   limits:
#     memory: 512Mi