#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
replicas: 1

image:
  # -- image repository
  repository: jaymoulin/jdownloader
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: latest

# -- environment variables. See more environment variables in the [emby documentation](https://emby.org/docs)
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # --Set MyJD Username
  MYJD_USER: "email@email.com"
  # -- Set MyJD Password > use secretKeyRef:
  MYJD_PASSWORD: SECRET
  # -- Set MyJD Devicename
  MYJD_DEVICE_NAME: JD

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- Disabled
service:
  main:
    enabled: false
    ports:
      http:
        port: 5800
        targetPort: 5800
  myjd:
    enabled: true
    ports:
      myjd:
        enabled: true
        port: 3129
        targetPort: 3129

# -- Enable and configure ingress settings for the chart under this key.
# @default -- Disabled
ingress:
  main:
    enabled: false

# -- Configures probes for the chart. Normally this does not need to be modified.
# @default -- Disabled
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: "/opt/JDownloader/app/cfg"
    existingClaim: jdownloader-config
  # -- use NFS for download folders
  media:
    enabled: false
    type: custom
    volumeSpec:
      nfs:
        server: 10.0.0.1
        path: /mnt/Media
    mountPath: /opt/JDownloader/Downloads
    readOnly: false


